language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix:
    - JULIAVERSION="julianightlies"
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'Pkg.init(); Pkg.clone("https://github.com/wildart/Distance.jl.git"); Pkg.clone("https://github.com/johnmyleswhite/NearestNeighbors.jl.git")'
  - julia -e 'Pkg.add("Distributions")'
  - julia -L src/InfoTheory.jl test/runtests.jl